### ISSUE TITLE
Monkey-Patching as Plugin Development for the Framework

### ISSUE THREAD

**Issue by dockerstack** [dockerstack/dockerstack-dashboard#20]
Should come up with a strategy on how to make plugin or hook based development for the framework either with Monkey-Patching or with any of the modules which extends the framework with new plug and play functionalities.

Reference URL - http://fredkschott.com/post/2014/09/nodejs-dangerous-module-design-patterns/

**Comment by kgrvamsi** [comment]
Will be of no use as we will be adding a plugin framework to the existing framework
